# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e604906b928cd2bdcdacf55803494740b6a3423977f574a15f48b1a25bbd8c6cd8e568e501fa6997a26f79414632cc248a0c539b51577da4f52cfde846fc3c2c

test:
  secret_key_base: 9a7f58e78d3133a5bd1db357b0cc7cb9179638f008ee3dd8b7e34ef942c5dac637f06d105e765c2065577aa424b7c322e57cb8ae045594b62a2ae2eeaf8c5528

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
